[package]
name = "engine"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
futures.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
parking_lot.workspace = true
dashmap.workspace = true
bloomfilter.workspace = true
rand.workspace = true
chrono.workspace = true
moka.workspace = true
uuid.workspace = true
once_cell.workspace = true
regex.workspace = true
reqwest.workspace = true
