pub mod calculator;
pub mod corridor;
pub mod event_pool;
pub mod filters;
pub mod fork_finder;
pub mod freebet;
pub mod generosity;
pub mod middle;
pub mod mirror;
pub mod momentum;
pub mod normalizer;
pub mod odds_errors;
pub mod value;
pub mod verifier;

pub use calculator::SurebetCalculator;
pub use corridor::CorridorFinder;
pub use event_pool::EventPool;
pub use filters::{ForkFilter, FilterPreset, LeaguesFilter};
pub use fork_finder::{ForkFinder, Fork, ForkLeg, ForkType, StakePlan, LegStake, ForkConfig};
pub use freebet::FreebetHunter;
pub use generosity::GenerosityIndexCalc;
pub use middle::MiddleDetector;
pub use mirror::MirrorDetector;
pub use momentum::MomentumScanner;
pub use normalizer::Normalizer;
pub use odds_errors::OddsErrorDetector;
pub use value::ValueDetector;
pub use verifier::OddsVerifier;
